{% set name = "plantismash" %}
{% set version = "2.0.0" %}
# Update this to the sha256 of the GitHub release tarball for v2.0.0 from YOUR repo
{% set sha256 = "d272d3d5643ed6a2ba48569f8204d9685be7be823b666258ea330639552e9d6b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/plantismash/plantismash/archive/refs/tags/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  # not noarch: you rely on many platform CLIs
  # install your package via pip (PEP 517)
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - plantismash = run_antismash:main

requirements:
  host:
    - python >=3.8,<3.9
    - pip
    - setuptools
    - wheel
  run:
    # Python/ABI
    - python >=3.8,<3.9

    # Python libs (all available on conda-forge/bioconda)
    - biopython >=1.76,<1.78
    - numpy >=1.24,<2
    - cssselect
    - pyquery >=2,<3              # 1.2.9 is not on conda for linux/osx; >=2 works with Py3.8+
    - svgwrite
    - openpyxl
    - networkx ==3.1
    - python-louvain ==0.16
    - bcbio-gff ==0.6.7
    - ete3
    - tqdm
    - logomaker
    - moods ==1.9.4.1             # MOODS-python on PyPI maps to 'moods' on conda

    # These two need to be packaged separately or vendored:
    # - helperlibs
    # - straight-plugin = 1.4.0.post1
    #
    # After adding recipes for them (recommended), uncomment:
    # - helperlibs
    # - straight-plugin ==1.4.0.post1

    # CLI tools (bioconda/conda-forge)
    - hmmer ==3.3.2
    - fasttree ==2.1.11
    - diamond ==2.0.15
    - muscle ==3.8.31
    - prodigal
    - blast ==2.12.0
    - cd-hit ==4.8.1
    - libxml2 ==2.10.3
    - pplacer
    - ncbi-datasets-cli
    - unzip
    # hmmer2 is old and label-specific; omit unless strictly required.
    # If truly required, consider gating it per-platform with selectors.

test:
  commands:
    - plantismash --help

about:
  home: https://github.com/plantismash/plantismash
  summary: "Detection of plant specialized metabolism gene clusters."
  description: |
    PlantiSMASH identifies and analyzes plant biosynthetic gene clusters,
    including expanded rules, substrate prediction for selected enzyme families,
    and TFBS detection.
  license: AGPL-3.0-or-later
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - elenadelpup