{% set name = "plantismash" %}
{% set version = "2.0" %}
{% set sha256 = "d272d3d5643ed6a2ba48569f8204d9685be7be823b666258ea330639552e9d6b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/plantismash/plantismash/archive/refs/tags/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - plantismash = run_antismash:main
  run_exports:
    - {{ pin_subpackage("plantismash", max_pin="x") }}

requirements:
  host:
    - python >=3.9,<3.12
    - pip
    - setuptools
    - wheel
  run:
    # Python / ABI
    - python >=3.9,<3.12

    # Python libs
    - biopython >=1.76,<1.78
    - helperlibs
    - pyquery >=2,<3
    - numpy >=1.24,<2
    - cssselect
    - svgwrite
    - openpyxl
    - networkx ==3.1
    - python-louvain ==0.16
    - bcbio-gff ==0.6.7
    - ete3
    - tqdm
    - logomaker
    - moods
    - straight-plugin ==1.4.0.post1

    # External CLI tools
    - hmmer >=3.3,<3.4
    - fasttree >=2.1.11
    - diamond >=2.0
    - muscle >=3.8,<3.9
    - prodigal
    - blast >=2.12,<3
    - cd-hit >=4.8
    - libxml2 >=2.10
    - pplacer
    - ncbi-datasets-cli
    - unzip

test:
  commands:
    - plantismash --help

about:
  home: https://github.com/plantismash/plantismash
  summary: Detection of plant specialized metabolism gene clusters.
  description: |
    PlantiSMASH identifies and analyzes plant biosynthetic gene clusters,
    including expanded rules, substrate prediction for selected enzyme families,
    and TFBS detection.
  license: AGPL-3.0-or-later
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - elenadelpup